### ISSUE TITLE
Theme Park (EU) and (USA)

### ISSUE THREAD

**Issue by altiereslima** [libretro/opera-libretro#108]
Pressing the L or R button in 4do-libretro
![theme park 4do](https://user-images.githubusercontent.com/18044879/44951537-4e052c00-ae3d-11e8-88e7-9f4c37dc574e.png)

Pressing the L or R button in  emulator 4do v1.3.2.4 (Windows 10)
![theme park 4do](https://user-images.githubusercontent.com/18044879/44951551-b8b66780-ae3d-11e8-8007-5bfc163b8ac8.png)

**Comment by trapexit** [comment]
Why did you close this?

**Comment by altiereslima** [comment]
the Crash 'n Burn hack that did this
