### ISSUE TITLE
Lemmings - Continuous static noise in ingame music/BGM

### ISSUE THREAD

**Issue by thorias** [libretro/opera-libretro#109]
There is a continuous annoying static noise in the in game musics (It starts just after the initial FMV intro, just when the DMA design logo appears). I know it is reported in the 4DO games compatibility list for version 1.3.0.1 but still occurs with the latest 1.3.2.4. 
It'll be good to have a look on fixing this. Tested only with 4DO libretro core.

Thanks!

**Comment by Cee123** [comment]
I second this, have also noticed the same thing with even the latest version.

**Comment by Cee123** [comment]
The music appears to be broken in this game. There are loops, blips, static and other kinds of audio issues there.
