### ISSUE TITLE
choppy sound issue

### ISSUE THREAD

**Issue by daniboiii** [libretro/opera-libretro#146]
I'm running the emulator on a raspberry pi 4, and it works really well, except for one thing. The sound intermittently cuts out. It seems to happen when the game gets too loud, as I can play a game like Twisted: The Game Show with very little cutting out except for louder bits like the clapping from the audience. On the other hand, the FMV intro for Killing Time cuts out almost constantly. Aside from this, I haven't encountered any issues, and this is the only emulator that I have seen this on.

**Comment by trapexit** [comment]
What's the frame rate when that happens? CPU usage? Typically choppy audio is the result of a lack of enough CPU performance.

**Comment by daniboiii** [comment]
I just looked at it and the CPU usage was very high. I apologize, this was a kind of last resort as I couldn't find information on this anywhere else.

**Comment by trapexit** [comment]
It doesn't mean there isn't a bug just that often, for games that others haven't reported issues for, is CPU. Have you tried tweaking the settings that may improve performance?

VDLP Pixel Format? VDLP Bypass CLUT? Make sure HiRes CEL Rendering is off? OperaOS SWI HLE (for some 3D games)?

**Comment by daniboiii** [comment]
Doing that significantly improved the issue. The cutting is still there but for most games it's improved a lot.
