### ISSUE TITLE
Not able to get second controller to work for 2-player.

### ISSUE THREAD

**Issue by oldgregoire** [libretro/opera-libretro#150]
I recently setup Retropie on a Rpi4-b & have lr-opera running as I’d like except for the issue of not being able to use a 2nd controller for 2-player on games like Primal Rage & Street Fighter.  I am not super computer literate so dont know coding but have been working at this Retropie project the past month & have researched so much that I feel confident in the basics of Retroarch/Retropie setup.  My controllers are mapped in Retroarch & both work fully in EVERY Retroarch core except for the 2-player gamepad in lr-opera.  Ive gone in & created a custom gamepad map for the controllers in Retroarch, it loads properly & 1-player operates as assigned in lr-opera but 2-player gamepad doesnt do anything despite both being recognized in every way throughout Retroarch.  I thought Id turn here to see if anyone had some insight or answers:)
The only thing I can think of being the problem is that on the original 3do system from Panasonic, the 2-player controller plugged into the 1-player controller itself.  There was only one input for a controller on the console & the 2 controllers were ‘daisy-chained’ off the 1st controller if that makes sense.  If the lr-opera emulation completely mimics the original software/hardware in everyway, is it gonna be possible to get 2 usb-controllers fully functioning in lr-opera if they are plugged in individually though Retroarch?  Is there a work-around or something simple that Im missing?  Any insight to solve this would be greatly appreciated, cheers!

**Comment by trapexit** [comment]
Did you increase the Active Input Devices option to 2 or more?

**Comment by oldgregoire** [comment]
Ohh god, Im a dummy - that was it!  Thank you so much for the help:)

**Comment by trapexit** [comment]
No problem. That needs to be fixed. Just haven't gotten around to fully analyzing the situation.
