### ISSUE TITLE
Game image size decreasing (Road Rash)

### ISSUE THREAD

**Issue by AlanRibas** [libretro/opera-libretro#152]
I'm not sure if that happens in other games.
But on "Road Rash". When starting the game, the game screen reaches the upper and lower edges of the monitor.
But after the race starts it gets slightly smaller. A little image is lost on top and bottom.
I circulated red to make it clearer. 
I already played this game on another emulator (Phoenix) and it doesn't happen there.

![20200608_205336](https://user-images.githubusercontent.com/16063712/84091699-96b32700-a9cb-11ea-8d14-5beeb04e1d33.jpg)

![20200608_205212](https://user-images.githubusercontent.com/16063712/84091712-9ca90800-a9cb-11ea-8435-1173c1cf9f06.jpg)

**Comment by trapexit** [comment]
Nothing is lost. There is a black border. It's there on original hardware.

![image](https://user-images.githubusercontent.com/197676/84092956-e3e0ca00-a9c6-11ea-8782-997a131a6f69.png)
![image](https://user-images.githubusercontent.com/197676/84092960-e7745100-a9c6-11ea-8c81-33927a9418cb.png)

**Comment by AlanRibas** [comment]
Wow. I didn't remember that !!
Thanks for clarifying ...

**Comment by trapexit** [comment]
On a TV with overscan (especially a CRT) it probably wouldn't be noticeable.
