### ISSUE TITLE
Support for CHD compress format?

### ISSUE THREAD

**Issue by virtual-man007** [libretro/opera-libretro#155]
lr-opera to support CHD compress format similar to other systems would be appreciated - save tons of space :)
Noticed m3u will be supported as well, looking forward!

**Comment by trapexit** [comment]
It supports it already. It has to be built for the platform in particular. It's upto the people building the core to enable it if appropriate for the platform.

**Comment by virtual-man007** [comment]
Interesting - using lr-opera on Raspberry Pi4 (retropie)
