### ISSUE TITLE
Neurodancer (Game) -Panasonic 3do (opera core) full speed support

### ISSUE THREAD

**Issue by merrychrishna** [libretro/opera-libretro#166]
## Description

when i play Neurodancer on Panasonic 3do (opera core), the intro seems to be nice and fast which is fine but when i go to play the game each of the interactive videos are super slow.

### Expected behavior

please can you add full speed support for Neurodancer?

### Actual behavior

the game is not operating at full speed

### Steps to reproduce the bug

in the main menu of Neurodancer, go to your messages and watch each of your video messages. each one is super slow and lagging so you can barely understand what the person is saying.

### Current core settings

in retroarch, disable REWIND
in retroarch>options change MADAM matrix engine to software
operaOS SWI HLE - enabled
threaded DSP - enabled

**Comment by trapexit** [comment]
Please, what platform? Specs? Etc.? It runs fine on PC. On an XU4 the message videos run a bit slow but are understandable. Something about how the game plays videos there requires more processing power than the intro and some others which seem to run fine. 

The MADAM mode and HLE will have no impact on non-3D games. Threaded DSP is experimental and not recommended. Could crash the emu. That said enabling it did increase the performance of the messages videos.

**Comment by merrychrishna** [comment]
this is on the anbernic rg351p handheld. newest retroarch and updated cores. on 351elec OS. Im not sure what the specs look like though on the 351p.

**Comment by trapexit** [comment]
That system is not powerful enough to run most games full speed. Sorry, but there really isn't anything that can be done without major rewrite so I'm going to close this ticket.
