### ISSUE TITLE
[BUG] Alone in the Dark - Audio Looping Issues

### ISSUE THREAD

**Issue by oblivioncth** [libretro/opera-libretro#182]
Once getting past the character introduction after starting a new game, portions of the music tracks get stuck looping continuously in segments that last about 3 seconds.

Seems to only affect some of the audio channels.

If the music is then disabled at any point, instead of actually stopping the entirety of the music then proceeds to loop the past second or so of the track until the music is re-enabled.

Some kind of buffer issue?

https://user-images.githubusercontent.com/24661585/211134358-da15c3d0-5c84-40b5-903b-a798a178a159.mp4

There is also a loud buzzing noise that occurs right after the 3DO logo fades (not shown in the video).

**System:**
- Windows 10
- Retroarch 1.14.0
- Core Version 1.0.0 8a49bb8
- BIOS: Panasonic FZ-1 (U)

All settings are default except that the Alone in the Dark timing hack is enabled (which does not affect the presence of this issue).

**Disk:**
<details>
  <summary>Alone in the Dark (US).cue</summary>
  
```
REM Ripping Tool: Trurip

CATALOG 0000000000000
FILE "Alone in the Dark (US).img" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00

REM DISC HASHES
REM CRC32 : 2c03e3af
REM MD5   : 192de93ff970cc04caa49d4a723a390f
REM SHA1  : d643c74677b283ec01431c6457d21f888747c77b

REM Gap Append Method: Prev [crc32]
REM Trk 01: 2c03e3af

REM Gap Append Method: Prev [md5]
REM Trk 01: 192de93ff970cc04caa49d4a723a390f

REM Gap Append Method: Prev [sha1]
REM Trk 01: d643c74677b283ec01431c6457d21f888747c77b

REM Gap Append Method: None [crc32]
REM Trk 01: 2c03e3af

REM Gap Append Method: None [md5]
REM Trk 01: 192de93ff970cc04caa49d4a723a390f

REM Gap Append Method: None [sha1]
REM Trk 01: d643c74677b283ec01431c6457d21f888747c77b

REM Gap Append Method: Next [crc32]
REM Trk 01: 2c03e3af

REM Gap Append Method: Next [md5]
REM Trk 01: 192de93ff970cc04caa49d4a723a390f

REM Gap Append Method: Next [sha1]
REM Trk 01: d643c74677b283ec01431c6457d21f888747c77b
```
</details>

**Comment by oblivioncth** [comment]
Should be a known issue, but figured I'd at least formally add this.

**Comment by trapexit** [comment]
Yeah, it's a known issue. A need to emulate a rarely used feature of the DSP.

**Comment by rtomasa** [comment]
Any plan on developing this missing feature? AITD is one of the most unique games in the system.

**Comment by trapexit** [comment]
Yes, when myself or someone has the cycles to do so.

**Comment by Andrew-Twins** [comment]
> Yes, when myself or someone has the cycles to do so.

Well, whenever the cycles come, know that there are a lot of people that would be deeply grateful. Me, for example. I really hope you will make us dream again fixing this issue with Alone in the Dark, Trapexit!

**Comment by CountCristoforo** [comment]
A youtuber named Patzawa has discovered how to fix this issue. It involves changing a line of code in the file clio.cpp. Here is a link to his YouTube video describing the fix as well as a screen shot of the code change that is required. I have no idea if this actually fixes the problem, just passing this along to people way more knowledgeable than me! I hope this helps! I feel the 3DO version is superior to the MS-DOS version of the game.

![image](https://github.com/libretro/opera-libretro/assets/153761692/de62e428-0aa1-43a0-aced-691e1759aec5)
https://www.youtube.com/watch?v=xmfcGUEmyqw&ab_channel=PATZAWA

**Comment by trapexit** [comment]
Thanks. I'll take a look.

**Comment by Andrew-Twins** [comment]
> Thanks. I'll take a look.

Thank you very, very much!

**Comment by oblivioncth** [comment]
I only did a brief test like in the shared video, but I can confirm the change does appear to fix the issue with no immediately discernable side-effects. 

```diff
--- a/libopera/opera_clio.c
+++ b/libopera/opera_clio.c
@@ -724,7 +724,7 @@ opera_clio_fifo_ei(uint16_t channel_)
           opera_clio_fiq_generate(1<<(channel_+16),0);

           /* reload enabled see patent WO09410641A1, 49.16 */
-          if(CLIO.fifo_i[channel_].next.addr != 0)
+          if(CLIO.fifo_i[channel_].next.addr != 0 && (CLIO.regs[0x304] & (0x1 << channel_)))
             {
               CLIO.fifo_i[channel_].start.addr = CLIO.fifo_i[channel_].next.addr;
               CLIO.fifo_i[channel_].start.len  = CLIO.fifo_i[channel_].next.len;

```

Might also be pertinent for `opera_clio.c:773`.

I have no bearing on of this is actually proper for emulating the co-processor, nor do I have a 3DO to test with, but at the very least it could be added as a hack if it can't be applied generally.

With the obligatory "download random binaries at your own risk", if anyone else wants to try it out on Windows...
[opera_libretro_dma_tweak.zip](https://github.com/libretro/opera-libretro/files/13669718/opera_libretro_dma_tweak.zip)

**Comment by Andrew-Twins** [comment]
I don't really understand shit about coding. But if this hack or mod could be added to the Retroarch core, that would be awesome!

**Comment by CountCristoforo** [comment]
Thank you! This game will be getting a lot of renewed interest when the remake drops early next year. This will be very helpful to many!

**Comment by rtomasa** [comment]
> ```diff
> if(CLIO.fifo_i[channel_].next.addr != 0 && (CLIO.regs[0x304] & (0x1 << channel_)))
> ```

Could you please detail the changes made in this DMA stopper section so that I can also test it in my linux machine?

Thanks

**Comment by rtomasa** [comment]
I confirm that it fixes Alone in the Dark sound issue. Tested in RPi5. I was testing more games with no apparent issues. Even more, I found out that Cyberia is now also playable. I was hanging to me in the first intro sequence on the sea. Now it is working fine.

**Comment by oblivioncth** [comment]
> I confirm that it fixes Alone in the Dark sound issue. Tested in RPi5. I was testing more games with no apparent issues. Even more, I found out that Cyberia is now also playable. I was hanging to me in the first intro sequence on the sea. Now it is working fine.

In reference to your original comment, as I'm sure you realized I just referenced the DMA stop section to speculate on why this change might be correct generally. The only actual change is on the line shown in the diff.

Otherwise, that's fascinating. When I initially went to add the change (which I tweaked the syntax of slightly due to personal preference) there was a typo present which caused Alone in the Dark to freeze after a fraction of a second after the sound starts in startup company FMVs, so games are clearly sensitive to DMA loops/reloads being stopped under the correct conditions.

**Comment by rtomasa** [comment]
Yes probably this is also why Cyberia was hanging too. I've tested it several times with original and patched core and only worked with the patch. And it is true that FMVs in general seem to transition faster than before

**Comment by CountCristoforo** [comment]
I was not able to replicate the hanging issue you are having in Cyberia. Game works fine for me with both versions of the core. I did notice this game breaks if you overclock the CPU. So I don't think the AITD fix affected this game at all. I wasn't able to find any previously known issue with Cyberia either.

**Comment by trapexit** [comment]
Thank you all for testing this. I'll do so later today and if I / we don't find any negatives I'll commit the change.

**Comment by rtomasa** [comment]
> I was not able to replicate the hanging issue you are having in Cyberia. Game works fine for me with both versions of the core. I did notice this game breaks if you overclock the CPU. So I don't think the AITD fix affected this game at all. I wasn't able to find any previously known issue with Cyberia either.

Maybe it is something specific on the platform and audio driver. I'm on linux ARM using ALSA driver. Anyhow, since the "issue" is that it now works, I won't comply on the same 😂

**Comment by CountCristoforo** [comment]
AITD fix also works on Lemmings!!! Issue #109 fixed!!!

**Comment by oblivioncth** [comment]
I was curious so I added log entries when the register 0x304 has bits cleared due to a poke at 0x308 (DMA stop), and when a input  FIFO is cleared due to the current channel's bit in said register being low (i.e. the patch). In both AITD and Lemmings any time the FIFO was cleared for this reason, a little bit higher up in the logs you can reliably find at least one (though often more) DMA stop being triggered for that same channel.

Basically, log snippets that more-or-less look like:

> [libretro INFO] [Opera]: DMA stopped with mask : 0x00000001
> ...
> [libretro INFO] [Opera]: DMA aborted due to channel stop: 0 (mask 0x00000001)

So hopefully this is the right move in general, though I get the impression that there's a little more to perfectly emulating this behavior than what's currently here. Of course, this is potentially a major improvement nonetheless.

I had a good chuckle at the irony of the lemmings issue being fixed by this:

> There is a continuous annoying static noise in the in game musics (It starts just after the initial FMV intro, just when the **DMA** design logo appears)

Very fitting.

**Comment by trapexit** [comment]
I just did a quick test and as reported by others both the demo and retail release of AitD music appear to be fixed by this. To be thorough I'm testing some other software to be sure it doesn't obviously screw anything up. I'm also going over Portofolio OS source to see how the OS used the DMA registers to see if anything stands out. In retrospect this is a semi-obvious fix but numerous people, including an original Freedo author, suggested the issue was likely missing DSP opcodes which was were I spent my time in the past investigating this. Thank you to everyone who have looked at this. Will commit something later today unless something crops up.

**Comment by CountCristoforo** [comment]
@trapexit Can anything be learned from the Phoenix Emulator? I bring it up because it has 100% compatibility. I'm not sure if the code for that project open source or not. I just kinda get the feeling that somebody figured all this 3DO stuff out a long time.

**Comment by rtomasa** [comment]
> I just did a quick test and as reported by others both the demo and retail release of AitD music appear to be fixed by this. To be thorough I'm testing some other software to be sure it doesn't obviously screw anything up. I'm also going over Portofolio OS source to see how the OS used the DMA registers to see if anything stands out. In retrospect this is a semi-obvious fix but numerous people, including an original Freedo author, suggested the issue was likely missing DSP opcodes which was were I spent my time in the past investigating this. Thank you to everyone who have looked at this. Will commit something later today unless something crops up.

Hope everything goes well in your tests because this is an easy workaround until the DSP opcodes are introduced.

**Comment by trapexit** [comment]
Phoenix is closed source... so not really. Also, Phoenix may loosely have "100% compatibility" but it is not 100% accurate to the hardware. 

> I just kinda get the feeling that somebody figured all this 3DO stuff out a long time.

Kinda... but not really. Phoenix was written by one of the people who worked on Freedo. It was only that small group of people who did the original reverse engineering. I am in close contact with one of those individuals but the source to later releases of Freedo (which later was used for Phoenix) are not going to be opened. Freedo was never written to be very accurate and Phoenix is in fact many ways a high level emulator. The fact there is an OS abstracting the hardware both makes emulation easier for general compatibility but harder for accuracy. Phoenix does a lot of high level emulation. Which is cool for seeing what software is doing but not for trying to ensure you have a truly accurate emulation. For instance: neither emulator emulates the MMU.

**Comment by trapexit** [comment]
> Hope everything goes well in your tests because this is an easy workaround until the DSP opcodes are introduced.

I'm not sure the issue with AitD is opcodes now that this has been brought up. The current code doesn't look correct to me. That said I'm also not positive the solution suggested is quite right either. It would seem to me that the check should happen before the next_addr check / reload. I'm testing both to see if I can tell a difference.

**Comment by oblivioncth** [comment]
> I just did a quick test and as reported by others both the demo and retail release of AitD music appear to be fixed by this. To be thorough I'm testing some other software to be sure it doesn't obviously screw anything up. I'm also going over Portofolio OS source to see how the OS used the DMA registers to see if anything stands out. In retrospect this is a semi-obvious fix but numerous people, including an original Freedo author, suggested the issue was likely missing DSP opcodes which was were I spent my time in the past investigating this. Thank you to everyone who have looked at this. Will commit something later today unless something crops up.

I was trying to look through WO09410641A1 for anything referencing the DMA stop function at 0x308 but nothings quite lined up so far so if you do find anything explicity covering this in the OS source it would be cool to see the reference.

**Comment by trapexit** [comment]
I tried moving the channel enabled check to the beginning of the function and got a lot more audio crackling. Unless there is something else funny it would seem that disabling the DMA doesn't stop it immediately but it runs till length == 0 either due to transfer or because it was set as such.

The patent mentions that neither addr or length can be zero but really don't say how zero is used. I put in an additional check for len==0 and exit just like addr==0 (with logging to see if it is triggered but I didn't see it in a few tests.) 

Another thing that isn't clear is the +4 being added to the length in the code. I removed that +4 and heard no difference but without a digital capture I can't be positive.

Regardless, while I still hear some pops occasionally at the end of samples and videos this clearly is better. I will do a bit more tidying up and testing and submit something soon.

**Comment by trapexit** [comment]
BTW... running Woody Woodpecker video I notice "DisableDMAChannel: DMA not stopped!" in the logs. The version of Portfolio source seems later than the version used and explicitly mention that log message being removed. I need to dig in a bit more to see if I can figure out what the condition was when that log would be printed.

**Comment by CountCristoforo** [comment]
Seal of the Pharaoh is a good example of audio crackling and popping. Happens every time you take a step in the game. Psychic Detective has some crazy audio crackling in it as well in the first few FMV sequences. Maybe these two games can help you figure out this weird audio issue.

**Comment by trapexit** [comment]
Still some crackles and pops and even a loop at the end of the char select screen dialog but this is clearly a lot better than before. I'll close this and #109 now and will spend some time looking over the DMA code later to see if those other issues can be resolved.

**Comment by oblivioncth** [comment]
> BTW... running Woody Woodpecker video I notice "DisableDMAChannel: DMA not stopped!" in the logs. The version of Portfolio source seems later than the version used and explicitly mention that log message being removed. I need to dig in a bit more to see if I can figure out what the condition was when that log would be printed.

That function doesn't seem to be present in your repo of the sources, other than a log message stating it was added. Did the function itself predate the version of the OS snapshot in the original source dump?

**Comment by trapexit** [comment]
> That function doesn't seem to be present in your repo of the sources, other than a log message stating it was added. Did the function itself predate the version of the OS snapshot in the original source dump?

Yes, that's what I was saying above. The changelog indicates it was removed in a previous release to what we have. Regardless, similar errors are found elsewhere and my guess is that the code was the same. It is simply looping reading start address register to catch when it stops changing. Apparently it is just a notification. Not an error.

**Comment by Andrew-Twins** [comment]
Thank you, Trapexit, and all of you for the testing as well. It is indeed way better than before.
