### ISSUE TITLE
[Request] add higher overclock option

### ISSUE THREAD

**Issue by QcSamuel** [libretro/opera-libretro#183]
the original 4do allowed to oc the 3do cpu up to 400%, some games need more than 200% to have higher and stable framerate

**Comment by trapexit** [comment]
There are complications with overclocking that high. What games in particular are you referring so it could be specifically tested?

**Comment by QcSamuel** [comment]
@trapexit i guess 30Mhz would be better exemple Doctor Hauzer and killing time
and yes there are complication with overclocking at 400% but why remove it if the original emu has it has a option

**Comment by trapexit** [comment]
4DO isn't "the original emu". FreeDO was. Regardless, a number of things changed when whoever ported 4DO to RetroArch. It wasn't "removed" so much as had to be reimplemented. Regardless, as I had referred to some titles don't behave properly when highly clocked and a number of subsystems need to be checked to ensure the overclocking works OK. Most things in the system are based on a primary clock. You can't just run it faster without accounting for how it impacts other aspects. Hence why I need to know what titles so it can be looked at when I or someone gets around to considering this.

**Comment by QcSamuel** [comment]
just noticed the option for 4x oc is there now thanks
