### ISSUE TITLE
Core option to toggle lightgun cursors

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/opera-libretro#186]
Hello, this is a continuation of what I saw in #180 and is a request for input instead of a feature request.

I made a core option to toggle all lightgun cursors on/off. It works as intended and allows users of absolute mice (Sinden Lightgun, Gun4IR, and the like) to play without cursors on screen.

I'm curious what the devs desire the core option to be. 

In its current state, the option toggles ALL 8 lightgun cursors on/off.

It may be advantageous to allow the cursors to be individually toggled in case someone has one absolute mouse and one relative mouse.

However, this is complicated by any connected guns possibly being anywhere in a chain of up to 8 devices. 8 toggles would still work fine, but at that point, the toggles should probably be put into a sub-menu.

Additionally, if the option goes that far, it may as well allow the user to choose the color for each cursor from the list of 8 colors given in the code (such as how lr-flycast handles this).

Just looking for some input. I can clean up my code and submit my current core option if an all-or-nothing toggle is desired or make it more complex like I mentioned above 😀

**Comment by trapexit** [comment]
The cursor should really be redone. I copied some of the setup from another core years ago. Unfortunately, there isn't something built into libretro (at least there hadn't been.) I think just a cross the board enable/disable is fine as a first pass. It unfortunately does get rather unwieldy pretty quick if you want to do more.

**Comment by Darknior** [comment]
Excellent idea, i love to see some updates on this emulator. The 3DO is really an unloved console, few developers work on it and updates are too rare.
A large part of the games still have lots of bugs, it's a shame ... there are only for the PSX and the others :(
If you can update guns @StormedBubbles i'm very interested. I love gun games.
With and without cross, but for now the cross is only a point, impossible to use and see it on screen for me :(
And for exemple, the Mad Dog McCree games have so many emulation lag, on a big computer too, and let them impossible to play :(

**Comment by StormedBubbles** [comment]
Okay; cool. I just submitted #187. Please feel free to comment on / edit anything you see fit. As far as I know, the only built-in cursor on the Libretro side is the GUI cursor when you enter the Quick Menu.

@Darknior I tend to stick to things purely on the Libretro side due to lack of experience with emulator code in general. I am happy to help out when I can with minor code additions and of course would love to help bug-test any future additions. I find these things fascinating, but I just feel more comfortable observing most of it.
