### ISSUE TITLE
Save State files not loading correctly

### ISSUE THREAD

**Issue by SedrynTyros** [libretro/opera-libretro#190]
When an auto state file is loaded the audio resumes but video is nothing but a black screen.

When loading a manual save state file, audio resumes and you see corrupt graphics near the bottom of the screen with most of the upper portion as a black screen.

Save States are borked.

**Comment by trapexit** [comment]
Please provide more information about the setup, game, platform. etc. 

Save state works fine on my x86_64 Linux setup.

**Comment by SedrynTyros** [comment]
The game is "Slayer (USA)". Setup is Windows 10, RetroArch 1.15.0.

The problem is core-specific. I have dozens of other cores and saves states function correctly for all of them. Opera is the only core with this problem.

**Comment by trapexit** [comment]
I just did a quick test in a VM with RA 1.15.0 installer on Win11 with Opera 1.0.0 8a49bb8 and save/load of save states looks to work fine with Slayer (and other titles.) 

How did you install RA?

**Comment by SedrynTyros** [comment]
When I have a chance, I'll confirm core version and test again.

**Comment by SedrynTyros** [comment]
Did a bit more testing. Curiously, the Save States do seem to work properly if I snap a save state and then reload that save state during that same RetroArch session.  However, if I close then relaunch RetroArch then try to load that same save state I end up with a blackscreen then graphics corruption along the bottom if the game transitions to a new screen. But the audio continues to play normally, lol. I'm not doing anything too fancy with the configuration and I have a couple of dozen configs setup this way for the other cores but none of them that have save state support seem to have this issue; only Opera

![image](https://github.com/libretro/opera-libretro/assets/11150165/d9ad3984-2250-4846-9caf-1eaa1436ed26)

**Comment by tacogerbil** [comment]
I'm having the same with every game I was testing FMV issues with (_I was testing it on Wing Commander III, Need for speed, Waialea golf, Road Rash_).. the auto loaded one seems to be the issue.  
I had to repeatedly undo the save state auto load as the video is corrupt while the audio plays.  
Opera 1.16.0 (1.0.0 100ae1e)... Whether it's the save state itself or the way it's being loaded... 🤔

**Comment by trapexit** [comment]
I'm already working on it.

**Comment by trapexit** [comment]
#197
