### ISSUE TITLE
Bad Core Options Prefix

### ISSUE THREAD

**Issue by rtomasa** [libretro/opera-libretro#192]
I found out that this core supports up to libretro options v1 format.
When using v1, `RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL` and `RETRO_ENVIRONMENT_SET_CORE_OPTIONS` are providing all core options with `opera_` prefix but `RETRO_ENVIRONMENT_GET_VARIABLE` is trying to read the old prefix `4do_` so this mismatch causes the core options not working at all. `4do_` should be changed to opera_ instead

**Comment by rtomasa** [comment]
From the code I saw that it is expecting NULL to check again for opera_ key

**Comment by trapexit** [comment]
Sorry, was this a problem or wasn't it? Yes, the code specifically was designed to check for the old 4DO core options to provide for some backwards compatibility when I renamed the core.

**Comment by rtomasa** [comment]
No problem at all. I'm developing a new libretro frontend from scratch and I was not returning NULL in the RETRO_ENVIRONMENT_GET_VARIABLE when option was not found, so the core was not requering for opera_ either. After fixing my callback function, it worked fine.
BTW (offtopic) is it safe to leave the opera_hack_timing_N enabled? could cause issues on other games?

**Comment by trapexit** [comment]
Yes, they can cause issues in some games though off hand I don't recall how/which.
