### ISSUE TITLE
DEFCON 5 crash at startup

### ISSUE THREAD

**Issue by fredgfgr** [libretro/opera-libretro#201]
since the last version, defcon 5 crashes after the intro and all the other games I have tried are at least twice as slow on my xiaomi pad 5

**Comment by hizzlekizzle** [comment]
Can you be a little more specific as to which version was the "last version"? RetroArch should have made a backup of the previous core, so can you try reverting back to it to get the git revision and verify that reverting fixes your issue?

**Comment by fredgfgr** [comment]
the last nightly version  with the retroarch update on android, the sound stuttering in need for speed and killing time with a big loss of fps compared to the previous version. je suis désolé, mais je n'ai pas le numéro exact de la version précédente.

**Comment by fredgfgr** [comment]
when i revert back with a save made the 3 january, defcon 5 doesn't crash and the speed of other games is ok

**Comment by hizzlekizzle** [comment]
Hmm, it seems the last update to the code occurred on Dec 31. When you loaded up the one from Jan 3, what does the name of the core say? The numbers after 1.0.0 are the "git hash", which tells exactly which revision of the code it was compiled from:
![image](https://github.com/libretro/opera-libretro/assets/2805586/c99b69bf-ab03-41c1-b46b-0da87e4fb4bc)

**Comment by trapexit** [comment]
Also, what are your settings?

**Comment by trapexit** [comment]
I think I figured out the crash at least though I need to dig a bit more.

Seem Defcon 5 may be putting bad data into the structure that is used for rendering but also tagging it to be skipped. I reworked some of this code while reworking the RAM stuff and before I think it would "fix" the issue but then skip it. Now it is trying to read the value (though I have asserts in the debug version). I was already preparing a cleanup patch of code in this function so I'll add it to it. Will look at the perf after.

**Comment by fredgfgr** [comment]
my backup of opera is : 673bd2a

**Comment by fredgfgr** [comment]
I just switched the threaded video option in the video settings to on (I had never used it before) and Opera even seems faster to me now. Thanks for taking time to respond to me, opera is a really great emulator.

**Comment by trapexit** [comment]
I meant the core options. There are cpu down/up clocking and other settings that could impact "performance" but nothing I've done recently really should have impacted perf by any meaningful amount. But since I changed the options it is possible that the defaults changed for you (which wouldn't be intentional).

**Comment by trapexit** [comment]
I've not really ever used RA on Android. How do you install nightly versions of cores? I'm not seeing it in the UI.

**Comment by fredgfgr** [comment]
![unnamed](https://github.com/libretro/opera-libretro/assets/86910685/5d8bc597-eb08-466c-838e-b610f3d1ac87)

**Comment by fredgfgr** [comment]
the cores are installed with the updater of retroarch (buildbot.libretro.com/nightly/android/latest/arm64-v8a/

**Comment by trapexit** [comment]
Should be fixed by #202
