### ISSUE TITLE
Need for Speed ... not start .. nvram error

### ISSUE THREAD

**Issue by Augusto7743** [libretro/opera-libretro#204]
Hello.
Thanks for reading my topic.
Linux Ubuntu 20.04.6 Retroarch 1.16 using opera core 26-01-2024.
The Need for Speed not start. In few seconds is showed an blank screen with message

NVRAM full : configuration not saved !

Not is possible start that game even deleting any nvram files in opera nvram folder.

Have an nice day.

**Comment by Augusto7743** [comment]
If starting NFS and when happen the bug enter the core options menu and change the BIOS to Europe and does and reset the game is started. After change BIOS to USA and restart and the game works.

**Comment by trapexit** [comment]
What are the precise BIOSes used?

**Comment by Augusto7743** [comment]
Thanks for replying.
FZ-10 (E) ANVIL No RSA
FZ-10 (U)

**Comment by trapexit** [comment]
Should be addressed in #216
