### ISSUE TITLE
Suggestion change information about MADAM in core options

### ISSUE THREAD

**Issue by Augusto7743** [libretro/opera-libretro#205]
Thanks for reading my topic.
In core options MADAM has the information in software mode can run more faster than in hardware mode.
In recent core versions the performance was changed being hardware mode is much more fast than in previous versions so the core information not is being accurate with current core version.
In some tests the hardware mode run more fast than in software mode.

Have an nice day.

**Comment by trapexit** [comment]
There has been no changes to how those work. There should be no differences. Please provide me with examples.

**Comment by Augusto7743** [comment]
Example is NFS
AMD FX 6300 3,5 GHZ 4 GB Ubuntu 20.04.6 GT 640 1 GB
core several previous versions need change the cpu power profile to performance to run in 60 FPS.
core current version using cpu profile power saver run between 51~56 FPS.
In several previous versions using cpu profile power saver run below 40 FPS.

Any optimization was done in MADAM code in recent versions and running in hardware mode is more faster than in software mode for NFS.
I have done few tests and all run more faster with MADAM in hardware mode.

**Comment by trapexit** [comment]
Again, nothing has changed with regard to this code. Regardless, the description says explicitly that "it has been observed that *some* games run faster" when using software. Nothing about that description is incorrect.

**Comment by Augusto7743** [comment]
PR #202 has cleanup MADAM code
https://github.com/libretro/opera-libretro/pull/202

Please my topic not is for point an error in description as an wrong action done, but for report really MADAM in hardware mode are running much more faster than before and more than software mode.
You have used the core current version ? Is much more faster than before.

**Comment by trapexit** [comment]
I am the author of these changes and maintainer of the project. Yes, I've used it.

That patch has nothing at all to do with the matrix engine. It is casual code cleanup.

**Comment by Augusto7743** [comment]
THANKS very much for doing that core =)
If that PR not was about optimization any other code has done an good performance improvement in opera core.
I use that core for more than one year never was possible run in 100 % speed using cpu profile power saver.
Exactly in same OS and hardware opera recent version are much faster.

Retroarch changes have done it ? well ... in any way I had to report it.
Again thanks very much for doing that core and have an nice day.

**Comment by Augusto7743** [comment]
@trapexit

I have done tests in some cores in retroarch 1.17 and opera core are much more faster than version from before 10-2023.

Again thanks for doing changes in that core.
