### ISSUE TITLE
Night Trap doesn’t load with shared NVRAM

### ISSUE THREAD

**Issue by Sirchadofwick** [libretro/opera-libretro#208]
If other games use the same shared NVRAM file that Night Trap attempts to load, the first disc of night trap does not load. It goes to a blank screen after the digital pictures logo and becomes unresponsive.

The only way to fix this is to delete the shared NVRAM file and then load the game again. The issue reoccurs if another game saves over the shared file and then attempt to reload Night Trap. This is probably related to the ‘storage is full’ issue that also happens on other games.

**Comment by trapexit** [comment]
Should be addressed in #216
