### ISSUE TITLE
Font(rom2) loading is broken, which makes some Japanese games such as Twinkle Knights (Japan) not working anymore.

### ISSUE THREAD

**Issue by SumavisionQ5** [libretro/opera-libretro#210]
Twinkle Knights (Japan) is broken in new version.
Firtst, this game requires Japanese font(Kanji) and BIOS to run. 
With same font and BIOS, game runs OK in old build (compiled in 2022 Dec.), but shows Game Over directly in lastest build, just like without necessary Japanese font.

**Comment by gigandes** [comment]
I'm also having the same problem on "Sword & Sorcery (JP)".
![ソード＆ソーサリー-240323-113932](https://github.com/libretro/opera-libretro/assets/64306369/86362db6-c05b-488d-8116-f132131750a3)

**Comment by SumavisionQ5** [comment]
Maybe the codes of ROM2 BIOS part is broken due to some commit?
@trapexit

**Comment by trapexit** [comment]
Should be fixed with #214 

Please check once updated.

**Comment by SumavisionQ5** [comment]
> Should be fixed with #214
> 
> Please check once updated.

It's fixed. Thanks a lot.
