### ISSUE TITLE
Feasibility of stand-alone, non-libretro ports?

### ISSUE THREAD

**Issue by Moonkeytest** [libretro/opera-libretro#217]
As you're likely aware, there's a great deal of people that don't like to use RetroArch, for various reasons.

I was wondering if there's any chance at all to have stand-alone, non-libretro ports to Windows and Linux.

**Comment by trapexit** [comment]
I barely have the cycles or interest to manage the project with all the benefits libretro offers. Not liking RA really isn't good enough for me to consider volunteering massive amounts of time to a new project. There are non-RA libretro launchers that can be used if you don't like RA.
